[package]
name = "merkle_hash"
version = "1.0.0"
edition = "2021"
authors=["Hristo_Gochev"]
description="Finds the Blake3 hash of files or entire directories using a Multithreaded Merkle tree algorithm"
license="MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.5.1"
blake3 = "1.3.1"
walkdir = "2.3.2"